name: ckb-next
base: core18
version: git
summary: |
    ckb-next is an open-source driver for Corsair keyboards and mice.
description:
    It aims to bring the features of Corsair's proprietary CUE software to the Linux and Mac operating systems. This project is currently a work in progress, but it already supports much of the same functionality, including full RGB animations. More features are coming soon. Testing and bug reports are appreciated!
grade: stable
confinement: strict
icon: ckb-next.png

apps:
    ckb-next-daemon:
        command: ckb-next-daemon
        daemon: simple
        plugs:
            - raw-usb

    ckb-next:
        command: desktop-launch ckb-next
        desktop: share/applications/ckb-next.desktop
        plugs:
           - unity7
           - home
           - desktop
           - desktop-legacy
           - raw-usb
           - x11
           - opengl
           - pulseaudio

parts:
    desktop-qt5:
        build-packages:
            - build-essential
            - qtbase5-dev
            - dpkg-dev
        make-parameters:
            - FLAVOR=qt5
        plugin: make
        source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
        source-subdir: qt
        stage-packages:
            - libxkbcommon0
            - ttf-ubuntu-font-family
            - dmz-cursor-theme
            - light-themes
            - adwaita-icon-theme
            - gnome-themes-standard
            - shared-mime-info
            - libqt5gui5
            - libgdk-pixbuf2.0-0
            - libqt5svg5
            - try: 
                - appmenu-qt5
            - locales-all
            - xdg-user-dirs
            - fcitx-frontend-qt5
    ckbbuild:
        source: https://github.com/ckb-next/ckb-next.git
        plugin: cmake
        build-packages:
            - build-essential
            - libudev-dev
            - qt5-default
            - zlib1g-dev
            - libappindicator-dev
            - libpulse-dev
            - libquazip5-dev
        stage-packages:
            - libquazip5-1
            - libudev1
            - zlib1g
            - libappindicator1
            - libpulse0
            - libblkid1
            - libbz2-1.0
            - libc6
            - libdb5.3
            - libgcc1
            - libgcrypt20
            - libgpg-error0
            - liblz4-1
            - liblzma5
            - libmount1
            - libpcre3
            - libselinux1
            - libstdc++6
            - libsystemd0
            - libtinfo5
            - libuuid1
        configflags:
            - -DCMAKE_INSTALL_PREFIX=/snap/ckb-next/current/
            - -DCMAKE_BUILD_TYPE=Release
            - -DDISABLE_UPDATER=1
        override-build: |
            snapcraftctl build
            mkdir --parents $SNAPCRAFT_PART_INSTALL/libexec
            mkdir --parents $SNAPCRAFT_PART_INSTALL/bin
            mkdir --parents $SNAPCRAFT_PART_INSTALL/share
            mv $SNAPCRAFT_PART_INSTALL/snap/ckb-next/current/bin/* $SNAPCRAFT_PART_INSTALL/bin/
            mv $SNAPCRAFT_PART_INSTALL/snap/ckb-next/current/libexec/* $SNAPCRAFT_PART_INSTALL/libexec/
            mv $SNAPCRAFT_PART_INSTALL/snap/ckb-next/current/share/* $SNAPCRAFT_PART_INSTALL/share/
        after: [desktop-qt5]
